version: '3.3'

services:

  postgis:
    build: ./postgis/
    environment:
      POSTGRES_PASSWORD: mysecretpw
      POSTGRES_DB: experiment
    expose:
       - 5432
    volumes: 
      - $PWD/data/postgis:/var/lib/postgresql/data
    container_name: postgis

  geoserver:
    build: ./geoserver/
    expose:
      - 8009
    environment:
      DB_BACKEND: POSTGRES
      HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DB: experiment
      POSTGRES_USER: postgres
      POSTGRES_PASS: mysecretpw
      GEOSERVER_DATA_DIR: /usr/local/tomcat/data
    volumes: 
      - $PWD/data/geoserver:/usr/local/tomcat/data
    container_name: geoserver

  mapstore:
    build: ./mapstore/
    expose:
      - 8080
    container_name: mapstore

  pygeoapi:
    build: ./pygeoapi/
    expose:
      - 80
    container_name: pygeoapi

  apache-httpd:
    build: ./apache-httpd/
    ports:
      - "80:80"
      - "443:443"
    container_name: apache-httpd
