version: '3.3'

services:

  postgis:
    build: ./postgis/
    environment:
      POSTGRES_PASSWORD: mysecretpw
      POSTGRES_DB: experiment
    expose:
       - 5432
    volumes: 
      - $PWD/data/postgis:/var/lib/postgresql/data
    container_name: postgis

  geoserver:
    build: ./geoserver/
    expose:
      - 8009
    environment:
      DB_BACKEND: POSTGRES
      HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DB: experiment
      POSTGRES_USER: postgres
      POSTGRES_PASS: mysecretpw
      GEOSERVER_DATA_DIR: /usr/local/tomcat/data
    volumes: 
      - $PWD/data/geoserver:/var/local/geoserver
      - $PWD/data/geoserver/gwc:/usr/local/tomcat/data/gwc
    container_name: geoserver

  mapstore:
    build: ./mapstore/
    expose:
      - 8080
    container_name: mapstore

  pygeoapi:
    build: ./pygeoapi/
    expose:
      - 80
    container_name: pygeoapi

  apache-httpd:
    build: ./apache-httpd/
    ports:
      - "80:80"
      - "443:443"
    container_name: apache-httpd

  openladap:
    build: ./openldap/
    expose:
      - 1389
      - 1636
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=openldap
      - LDAP_USERS=antonio,joana
      - LDAP_PASSWORDS=antonio,joana
      - LDAP_ROOT=dc=emotionalcities,dc=org
      #- LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt
      #- LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key
      #- LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/openldapCA.crt
    volumes:
      - $PWD/data/openldap/dataz:/bitnami/openldap
      #- $PWD/data/openldap/certs:/opt/bitnami/openldap/certs
    container_name: openldap
